### ISSUE TITLE
When Inbound Form has no name fields it is using the form name as a first name.

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#100]
![image](https://cloud.githubusercontent.com/assets/2002207/5867287/adfab6fe-a25f-11e4-98a8-87050116a3d1.png)

In the image above 'Say Yes' is the name of the form. 

This issues needs to be confirmed and addressed.

**Comment by atwellpub** [comment]
@DavidWells where should kirit look to edit the automapping to make sure the form name is not interpreted as a first/last name?

**Comment by DavidWells** [comment]
You can't edit anything without gulp

**Comment by atwellpub** [comment]
really? Will you be more descriptive? I'm not sure what you are saying. Is all JS off limits now?

**Comment by DavidWells** [comment]
Install gulp and I can show you

```

sudo npm install -g gulp



On Thu, Jan 22, 2015 at 4:03 PM, Hudson Atwell <notifications@github.com>
wrote:

> really? Will you be more descriptive? I'm not sure what you are saying. Is
> all JS off limits now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inboundnow/leads/issues/100#issuecomment-71124908>.
>

**Comment by atwellpub** [comment]
Added my documentation on how to install GULP. It's basic, but may help someone get started:
http://docs.inboundnow.com/guide/contributing-inbound-now-codebase/
