### ISSUE TITLE
[Lead Management] Upgrade to OOP + Bonus features

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#109]
Upgrade Lead Management code structure to OOP.

Added these improvements:

* automatically detects custom taxonomies and allows for their advanced filtering. 

I discovered that the tag search system was not operable. I did not add it back in. It needs to be re-factored at a later date.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/leads/commit/fd46a9100041b7852be715391734aa3a2d2399a4

**Comment by atwellpub** [comment]
* Add & remove tags need restoration. 
* After action same search result page should load.

**Comment by DavidWells** [comment]
Notice: Undefined variable: query in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/leads/classes/class.lead-management.php on line 324

Notice: Trying to get property of non-object in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/leads/classes/class.lead-management.php on line 324

**Comment by DavidWells** [comment]
Also default text is showing when it shouldn't: http://www.screencast.com/t/N29yl6IjZwLM

**Comment by DavidWells** [comment]
Also: http://www.screencast.com/t/iO169kDGbQ

Undefined variable: tags in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/leads/classes/class.lead-management.php on line 450

**Comment by atwellpub** [comment]
https://github.com/inboundnow/leads/commit/5e734dd6fb266345f9eb32ca7eccd8dce7b43c81 

^ Should cover the latest bugs
