### ISSUE TITLE
Fatal in Leads

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/leads#114]
We got a fatal in leads on install. Do you see the problem in https://github.com/inboundnow/leads/blob/master/leads.php#L92-L101

Not sure I got the file_exists correct

Warning: require_once(/nas/wp/www/cluster-1133/davidwells/wp-content/plugins/_inbound-pro/core/shared/classes/class.load-shared.php) [function.require-once]: failed to open stream: No such file or directory in /nas/wp/www/cluster-1133/davidwells/wp-content/plugins/leads/leads.php on line 97

Fatal error: require_once() [function.require]: Failed opening required '/nas/wp/www/cluster-1133/davidwells/wp-content/plugins/_inbound-pro/core/shared/classes/class.load-shared.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/wp/www/cluster-1133/davidwells/wp-content/plugins/leads/leads.php on line 97

**Comment by atwellpub** [comment]
I made a change to it. I think what is there should be enough.

**Comment by DavidWells** [comment]
Fixed in SVN.

Need a permanent solution for Pro though

**Comment by atwellpub** [comment]
It should work well with pro.It calls /core/shared/ if pro is active and running.
