### ISSUE TITLE
Failed geolocation connection causes fatal error. 

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#120]
Geolocation connect was causing a fatal error. Will need to investigate this further to make sure it's still working and not an isolated incident with the client. 

Leads were still making it in, but the inbound_store_lead_post function was not running causing some third party integrations not to fire. 

* [x] Fix issue with fatal
* [x] Test geoplugin connect to see if it still works ( service is down )
* [x] Temporarily remove geolocation services
* [ ] Maybe offload this connect to when the lead profile is loaded for the first time rather than during lead storage to shave time.

Ideally a replacement would be a service provided by Google API or another major provider.

**Comment by atwellpub** [comment]
Possible replacements:
http://stackoverflow.com/questions/409999/getting-the-location-from-an-ip-address

**Comment by DavidWells** [comment]
Can we turn this back on but get the actual address when the person views the lead and not on lead save?

**Comment by atwellpub** [comment]
I'm not sire if the Geoip.net service is back up or now. But if it is, we can. I need to test somewhere besides localhost to find out.

**Comment by atwellpub** [comment]
ok have it back in.

**Comment by DavidWells** [comment]
where does the check happen?

**Comment by atwellpub** [comment]
Where the look up is happening
https://github.com/inboundnow/leads/blob/master/classes/class.metaboxes.wp-lead.php#L77
https://github.com/inboundnow/leads/blob/master/classes/class.metaboxes.wp-lead.php#L240-L322

Where the IP is stored:
https://github.com/inboundnow/leads/blob/master/shared/classes/class.lead-storage.php#L164-L168

There's a lot of aspects of leads that should be refactored and gone over, but this is how it's handled at the moment.
