### ISSUE TITLE
Question: what does this code hook into? 

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#125]
I can't find a use case in the core code:

https://github.com/inboundnow/leads/blob/d24ecf2c598c973cabd75dc91f701e3c06bd4bfe/modules/module.tracking.php#L36-L62

**Comment by DavidWells** [comment]
if email used in querystring the lead ID is set.

site.com?wpl_email=hudson@codes.com will set your lead cookie ID to correct
ID

**Comment by atwellpub** [comment]
Ok thank you. 

What about this one? I can't find it used in the code.

https://github.com/inboundnow/leads/blob/d24ecf2c598c973cabd75dc91f701e3c06bd4bfe/modules/module.tracking.php#L144-L166

**Comment by DavidWells** [comment]
wpleads_check_url_for_queries was for parsing traffic from search engines. I don't think it was ever implemented because of the changes google made to anonymize the keyword data from referral URLs
