### ISSUE TITLE
Restoring Lead Logs

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#130]
It wasn't hooked up for some reason. Not sure how long it has been offline. Restoring.

**Comment by DavidWells** [comment]
Nah nah nah the logs are just the post meta now. It was the way it was supposed to be in that guys video...

**Comment by DavidWells** [comment]
The raw form logs are gone due to sensitive information being accidentally stored in them.

Logs tab is essentially the WordPress custom meta display

**Comment by atwellpub** [comment]
Ok reversing that. Will you help me find the code that puts the custom fields inside the log tab? I can't seem to find it in 1.7.1 https://github.com/inboundnow/leads/tree/1.7.1 and I've lost it during the refactor.

**Comment by DavidWells** [comment]
Its in the JS somewhere.

There were a ton of things broken from the landing page refactoring as well...

How are you refactoring? The JS and stuff needs to stay the same or things will break

**Comment by atwellpub** [comment]
I'm standardizing the way we store assets across all the plugins. Mostly what that means is moving js css files into the /assets/ folder. 

Other ways I am refactoring is converting code into OOP. Please make an issue if something's not right and I'll look into it. 

Log issue seems to have sorted and been restored.
