### ISSUE TITLE
Making the plugin self contained..

### ISSUE THREAD

**Issue by vimes1984** [inboundnow/leads#131]
line 60 of 'wp-content/leads/shared/assets/assets.loader.class.php' requires jquery, in my case my theme is concatenating all the js files and de_registering jquery, this causes the plugin to fail... 
Any ideas of making this completly self contained at some point?

**Comment by atwellpub** [comment]
We do have a plan to convert as much jquery to pure javascript as possible. But jQuery is so accepted these days, and it's a great tool. We do need this class to be available on the frontend too. Can you modify your theme to make it compatible?

**Comment by vimes1984** [comment]
I've actually modified the plugin to require my concated js file including
jquery...

**Comment by vimes1984** [comment]
have you thought about offering to allow a option to allow users to not use the wordpress jQuery ? 
maybe a checkbox that can read along the lines of: 
Do you wish to load your own version of jQuery?
Am I the only person to un register the default wordpress jquery and concatnate the my js?

**Comment by atwellpub** [comment]
So far yes that I know of. We have dependencies on jQuery that we can't avoid at the moment. 

I don't understand the core of the issue though. Why does the theme take protocol to deregister jquery?

**Comment by vimes1984** [comment]
theoretically, the less number of http requests the better, so by running grunt in my theme build I'm concataning all of my JS files including jquery. Which I belive is relatively common practise, to accomodate this I'm deregistering jquery in my theme files which in turn causes leads to break since it has a dependency on jquery...

**Comment by atwellpub** [comment]
Can you craft your theme to leave an exception for WordPress's core jquery file?

**Comment by vimes1984** [comment]
yes of course I could, but that would defeat the purpose of concatinating
all the scripts..

**Comment by atwellpub** [comment]
It wouldn't be perfect. But why not concatenate jQuery along with the other scripts?

**Comment by vimes1984** [comment]
and here lies the crux of the argument to concatante the jQuery with my
other js files I have to then DEREGISTER jquery from the wordpress, causing
your plugin to break :D

**Comment by atwellpub** [comment]
oh because of the requirement. I understand. Is there any way to fake the enqueue in a way that does not cause any extra load time?

**Comment by vimes1984** [comment]
not that I know of ....
hence my appearance here on this thread!
:D

**Comment by atwellpub** [comment]
well you could register an empty file into the jquery namespace. It's still an http request but at least jquery gets concatenated and and leads gets tricked... What do you think?

**Comment by vimes1984** [comment]
Not the cleanest of solutions:D
For now I've just edited your core plugins files and noted on my repo what
I've changed so as to apply the same changes after update.

**Comment by atwellpub** [comment]
that's a dangerous road though considering the upkeep requirements and the amount of updates we  deploy. If it's a client site it might set the client up for eventual break down.

**Comment by atwellpub** [comment]
We won't have a pure JS setup until the middle of next year probably. It is one of our goals though.

**Comment by vimes1984** [comment]
I've version controlled the theme and it's one edit in your files and it's
docuemnted. I'm the only person updating it.
I dodn't even need a full Js version just the ability to not require the
jquery dependency on your front end files...
or the ability to require a different file handle that isn't jquery...

**Comment by vimes1984** [comment]
I may fork it this weekend and apply it myself...


On 20 August 2015 at 19:18, Christopher J.Churchill <churchill.c.j@gmail.com
