### ISSUE TITLE
Lead storage class question

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#137]
This looks permanently off:
https://github.com/inboundnow/landing-pages/blob/master/shared/classes/class.lead-storage.php#L124-L128

Is it in preparation for something?

**Comment by DavidWells** [comment]
Lead storage needs a revamp for how inbound forms handle lead submissions.

We are currently running an ajax call + processing the POST on form
submission.

I'd like to clean it up eventually.

But yea this is disabled for now. No eta on when I can tackle this

**Comment by atwellpub** [comment]
Ok closing for now. Mind if I remove it?
