### ISSUE TITLE
PHP Fatal error:  Call to undefined function cal_days_in_month()

### ISSUE THREAD

**Issue by edo888** [inboundnow/leads#138]
File is plugins/leads/classes/class.dashboard.php on line 366

**Comment by atwellpub** [comment]
cal_days_in_month is a native php method:
http://php.net/manual/en/function.cal-days-in-month.php

Not sure what is going on for you. Old version of PHP maybe?

**Comment by edo888** [comment]
It seems I do not have calendar library compiled with PHP.

**Comment by atwellpub** [comment]
Thank you for the information. This is rare, but it's something that your hosting administrator should be able to help you with. I'm going to close this ticket, you are welcome to update it with comments if you like.
