### ISSUE TITLE
Google map doesn't load on the lead page

### ISSUE THREAD

**Issue by edo888** [inboundnow/leads#139]
Is it a default feature or it requires some configuration?

Where does it store the lat/lng data if available?

Thanks!

**Comment by atwellpub** [comment]
It's disabled at the moment for the released public files through WordPress. But for the master branch:

https://github.com/inboundnow/leads/blob/master/classes/class.metaboxes.wp-lead.php#L237-L326

**Comment by edo888** [comment]
Great! Thanks!
