### ISSUE TITLE
Notification box not dismissed correctly

### ISSUE THREAD

**Issue by daprela** [inboundnow/leads#142]
The notification box (the one notifying of the deprecated email notification system) is dismissed in a strange way. If I click to dismiss it I'm sent to the posts editor page (/wp-admin/edit.php), with the notice box still visible. Only here if I dismiss the notification box it becomes permanent

**Comment by atwellpub** [comment]
I wasn't able to get this one to send me to the posts page, but I did find out what would cause the double dismiss issue and took care of it. I also moved the notification from the class.post-type.php file to the class.notifications.php file.
