### ISSUE TITLE
[inbound forms] Checboxes as required field revamp

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#96]
Currently if a checkbox field is marked as required then we only mark the first checkbox field as required. Otherwise all checkboxes will be required. Anyway the systems does not make sense to me right now. What it is now is a hack added in for a customer because there was zero requirement support for checkboxes at one time and the customer wanted an agreement checkbox.

In the future we need to make sure validation for checkboxes means at least one checkbox is clicked.

**Comment by atwellpub** [comment]
Hey Kirit,

So far so good. Here's the review and critique with some more instruction:

### needs addressing
* Indentation needs fix http://screencast.com/t/3Heeoi4s5pMf
* Because this work is in the /shared/ folder, we need to perform it on the 'calls to action' plugin. I've created a [document](http://docs.inboundnow.com/guide/contributing-inbound-now-codebase/) with more information. Sorry I have not told you this sooner, I had not had time yet. 

### Request
* Use PHP to make language strings i18n ready with the namespace 'cta'. https://github.com/kiritDholakiya/leads/blob/26a56713af6d2f883ffd3a1ffe05e06d5a702df1/shared/classes/class.form.php#L450 (look for any other language strings that need to be made i18n ready. 


Then make a merge request to merge your local changes into our main repository and I'll accept the merge request and close the issue.

**Comment by atwellpub** [comment]
Also Kirit, 

I noticed you forked the repository. This is how we want people who are not employees to contribute, but for you It would be much better if you created your local repositories from our main repos instead of forking them. 

I have given your account permission to write commits to them. This way you do not have to keep a separate code base and make merge requests, which will cause you to spend much time staying in sych. 

What I will ask you to do is to work with our repositories directly, but use SourceTree to manage them and whenever working on a new issue use SourceTree's 'GitFlow' to start 'New Features' for every issue you address. Then we can merge feature branches into our main branches once they are complete.

http://blog.sourcetreeapp.com/2012/08/01/smart-branching-with-sourcetree-and-git-flow/

**Comment by DavidWells** [comment]
Hey @kiritDholakiya just a heads up. 

We follow these php formatting guidelines: https://make.wordpress.org/core/handbook/coding-standards/php/ and these standards for JS: https://github.com/airbnb/javascript

**Comment by kiritDholakiya** [comment]
Thanks, i will follow this guideline while working in plugins....

Thanks and Regards,
Kirit Dholakiya
+91 7698822655

**Comment by atwellpub** [comment]
Bug: 
https://github.com/inboundnow/cta/blob/master/shared/classes/class.form.php#L433

When no checboxes present then alert gets fired.
